### PR TITLE
add sf3 support

### PR DESCRIPTION
**Pull request by Devolicious**

### CODE REVIEW

**Comment by sgomez** [comment]
It is not enough. The file _services.yml_ must be updated and the arguments must be quoted or a ParseException will be throwed. In 2.8 we can found some deprecation messages like this:

```
Not quoting the scalar "@knp_rad_fixtures_load.schema_tool" starting with "@" is
deprecated since Symfony 2.8 and will throw a ParseException in 3.0
```

I suggest to change it to xml format to avoid this problem.

**Comment by akerouanton** [comment]
@Devolicious Please can you fix your PR ? As stated by @sgomez, service references in [services.yml](https://github.com/KnpLabs/rad-fixtures-load/blob/master/src/Knp/Rad/FixturesLoad/Resources/config/services.yml) should be quoted.

**Comment by sgomez** [comment]
@NiR- I did a fork with this [on my own fork](https://github.com/sgomez/rad-fixtures-load/tree/sf3-support). Is there a way I can modify this PR? If not, if you want, I'd like to send a new one with this issue resolved.

**Comment by akerouanton** [comment]
@sgomez Feel free to create a new PR and I will merge it, since there is no activity on this one.

**Comment by sgomez** [comment]
@NiR- done in #25. Thanks!

**Pull request closed without merging**
