### PR TITLE
Added support for PHP fixtures in additions to YML fixtures

### PR DESCRIPTION
**Pull request by mwansinck**
Alice supports PHP fixtures by default, so this bundle should also;
see: https://github.com/nelmio/alice/blob/2.x/doc/complete-reference.md#creating-fixtures

### CODE REVIEW

**Comment by mwansinck** [comment]
Any update?

**Comment by mwansinck** [comment]
@PedroTroller could you please evaluate this PR

**Comment by PedroTroller** [comment]
Thanks a lot. Sorry for the delay. Your contribution is the version 1.6.0

**Comment by mwansinck** [comment]
Great. thank you

**Pull request merged**
